name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get repository information
        uses: actions/github-script@v6
        with:
          script: |
            const repo = context.payload.repository.full_name;
            console.log(`The repository is ${repo}`);

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make tar

      - name: Download and extract CEdev
        run: |
          curl -sL https://github.com/CE-Programming/toolchain/releases/latest/download/CEdev-Linux.tar.gz | tar xz
      
      - name: Add CEdev to PATH
        run: |
          echo "CEdev/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH
      
      - name: Make GFX
        run: make gfx

      - name: Build TINET.8xp
        run: make

      - name: Upload TINET.8xp
        uses: actions/upload-artifact@v3
        with:
          name: TINET.8xp
          path: bin/TINET.8xp

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}

      - name: Create Development Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: development-UNSTABLE
          name: Development Release - UNSTABLE
          body: This is an unstable development release.
          draft: false
          prerelease: true

      - name: Add TINET.8xp to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/TINET.8xp
          asset_name: TINET.8xp
          asset_content_type: application/octet-stream